### PR TITLE
Avoid methods from ActiveSupport, which is not required at runtime

### PR DESCRIPTION
**Pull request by aprescott**
Version 3.0.0 included #109 which added the private `unwrapped_job_options` method:

```ruby
def unwrapped_job_options(jobs)
  jobs = jobs.values if jobs.is_a?(Hash)
  jobs.flatten.map do |job|
    job.slice('at')
  end
end
```

The method relies on `Hash#slice`, which is in ActiveSupport but not Ruby. This broke one of my gem's test suites because the `activesupport` gem isn't declared as a runtime dependency, only a development dependency, causing a `NoMethodError`:

```
Failure/Error: expect(FooJob).to have_enqueued_job(1)

NoMethodError:
  undefined method `slice' for #<Hash:0x000000027b2df0>
# ./gemfiles/vendor/bundle/ruby/2.0.0/gems/rspec-sidekiq-3.0.0/lib/rspec/sidekiq/matchers/have_enqueued_job.rb:140:in `block in unwrapped_job_options'
```

I would actually like to avoid _any_ runtime gem dependencies on ActiveSupport or other Rails libraries, since Sidekiq itself does not require Rails.

In addition to the use of `slice`, `present?` was also introduced in #81, which is only in ActiveSupport.

This PR corrects both problems.

It would be nice to have this be caught by the test suite, but I don't see a simple way of avoiding it because of the global nature of `require`. The reason it doesn't fail in this gem's own suite is because `activejob` is a development dependency, presumably to allow test coverage of ActiveJob support.

### CODE REVIEW

**Comment by aprescott** [comment]
I branched this off `develop`, on the assumption that it shouldn't be in `master`, which is behind `develop` right now and doesn't include the v3.0.0 commit. Let me know if `master` gets updated and I should use `master` as the base instead.

**Comment by packrat386** [comment]
Thanks for sending this. I'll release 3.0.1 with this fix soon.

**Comment by aprescott** [comment]
Thanks!

**Comment by packrat386** [comment]
That's released now. https://github.com/philostler/rspec-sidekiq/releases/tag/v3.0.1

**Comment by aprescott** [comment]
Perfect, thanks!
